/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/theme/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alarms.styles` | `/alarms.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings.styles` | `/settings.styles`; params?: Router.UnknownInputParams; } | { pathname: `/components/tabs/settings`; params?: Router.UnknownInputParams; } | { pathname: `/components/tabs/alarms`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alarms` | `/alarms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/theme/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alarms.styles` | `/alarms.styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings.styles` | `/settings.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/components/tabs/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/components/tabs/alarms`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alarms` | `/alarms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/theme/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alarms.styles${`?${string}` | `#${string}` | ''}` | `/alarms.styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings.styles${`?${string}` | `#${string}` | ''}` | `/settings.styles${`?${string}` | `#${string}` | ''}` | `/components/tabs/settings${`?${string}` | `#${string}` | ''}` | `/components/tabs/alarms${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alarms${`?${string}` | `#${string}` | ''}` | `/alarms${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/theme/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alarms.styles` | `/alarms.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings.styles` | `/settings.styles`; params?: Router.UnknownInputParams; } | { pathname: `/components/tabs/settings`; params?: Router.UnknownInputParams; } | { pathname: `/components/tabs/alarms`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alarms` | `/alarms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
